### ISSUE TITLE
error Object(...) is not a function

### ISSUE THREAD

**Issue by Wendenburg** [kripod/react-hooks#268]
## Description

using useSize I get the following error in a Typescript setup:
**Object(...) is not a function**

## Reproduction

```
const imageRef = useRef(null);
const [width, height] = useSize(imageRef);
return <img ref={imageRef} srcSet={`${src} 1x`} src={src} />;
```

## Expected behavior

There should be no error

## Actual behavior

adding the line with useSize results in the above error, without everything is working

## Environment

Not sure if this works properly:

## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
 - Memory: 135.68 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 14.15.4 - /usr/local/bin/node
 - Yarn: 1.22.5 - ~/.yarn/bin/yarn
 - npm: 6.14.10 - /usr/local/bin/npm
## Browsers:
 - Chrome: 89.0.4389.90
 - Firefox: 86.0
 - Safari: 13.1.2

React: 16.3.1, 
web-api-hooks: "^3.0.2",

**Comment by Wendenburg** [comment]
found my mistake, my bad, all good!

**Comment by kripod** [comment]
Thanks for closing this issue. I’m glad that you could fix it 😊
