### ISSUE TITLE
Rename the project due to popular demand

### ISSUE THREAD

**Issue by kripod** [kripod/react-hooks#77]
As discussed on Reddit, the word "standard" may confuse some users:

> [Seeing the word "standard" in the name gives me flashbacks of the so-called "standard" config for ESLint which was not at all standard and quite opinionated in parts.](https://www.reddit.com/r/reactjs/comments/d4mnvk/announcing_standardhooks_for_convenient_web_api/f0hlp2f/) – [qeBhuajX5JAooqbRNiNv](https://www.reddit.com/user/qeBhuajX5JAooqbRNiNv/)

I am open towards further discussion, listening to any viable alternatives which would eliminate bad feelings related to branding. The only requirement is that the name has to be generic enough to cover all the aspects of the library.

**Comment by moljac024** [comment]
- pocket-hooks
- swiss-army-hooks
- kitchen-sink-hooks
- kitchen-hooks
- hooksorama
- hooks-and-beyond

**Comment by fmoliveira** [comment]
browser-api-hooks ¯\\\_(ツ)\_/¯

**Comment by srdjan** [comment]
"Essential set of React Hooks for convenient _**Web API**_ consumption." => web-api-hooks

**Comment by Jose4gg** [comment]
hooky

**Comment by Jfelix61** [comment]
utility-hooks

**Comment by kripod** [comment]
Thanks for all the suggestions! There is a [discussion](https://www.reddit.com/r/reactjs/comments/deipgo/due_to_popular_demand_standardhooks_is_being/) over Reddit with some interesting suggestions. I'm considering to split the package in half, providing:

- Web API hooks
- State hooks

In the form of a monorepo.

**Comment by fmoliveira** [comment]
I think that split makes a lot of sense @kripod !

**Comment by kripod** [comment]
The transition to a monorepo-based structure will be aligned with the release of v2. The package `standard-hooks` is going to be deprecated in favor of:

- [`web-api-hooks`](https://yarnpkg.com/en/package/web-api-hooks), containing sensor, storage and scheduling-related, specification-dependent hooks
- [`state-hooks`](https://yarnpkg.com/en/package/state-hooks), offering custom utilities for state management

**Comment by kripod** [comment]
Unfortunately, `standard-hooks@1.4.0` was published with a failure, thus, `standard-hooks@2.0.0` will be released and deprecated as soon as `web-api-hooks` and `state-hooks` are available.

**Comment by kripod** [comment]
Version 2 has been officially released, with changelogs available for [web-api-hooks](https://github.com/kripod/react-hooks/releases/tag/web-api-hooks%402.0.0) and [state-hooks](https://github.com/kripod/react-hooks/releases/tag/state-hooks%402.0.0). Thanks for the overwhelming support I got from everyone!
